### ISSUE TITLE
Add `isUserInteractionEnabled`

### ISSUE THREAD

**Issue by olegtverdyy** [quanshousio/ToastUI#33]
## Pre-requisites:

* [ ] No, I did not find what I was looking for

## Feature Suggestion

After having implemented the toast library I have found myself with the need for the user to be able to click inside the view in which it is presented so that he can perform certain actions while the Toast view is present.

## Possible Implementation

I add a link to my repository so you can make a merge to yours.(https://github.com/quanshousio/ToastUI/compare/main...olegtverdyy:ToastUI:feature/add-isUserInteractionEnabled)

## Context

- I present a toast at the bottom of the screen.
- The user tries to click on another option on the screen to perform a navigation.
- As the toast is displayed, he is not allowed to do so.

For it I have enabled the `isUserInteractionEnabled` option, to allow the user to make this action.

**Comment by quanshousio** [comment]
Hi @olegtverdyy, thanks for your suggestion.

I tried your implementation on latest iOS 17.4 and I was not able to perform actions outside of the presenting toast view. It appears that the default setting for `isUserInteractionEnabled` in `UIWindow` is already true, if I recall correctly. Moreover, this problem seems more involved than just setting that flag.

Would you mind providing a detailed example on how are you presenting the view? Thanks!

**Comment by quanshousio** [comment]
This issue has been closed due to inactivity. Please feel free to reopen it if you have any further questions.
